version: "3"

services:
  fastapi:
    build: 
      context: ./api
    ports:
      - "8000:80"
    depends_on:
        questiondb:
            condition: service_healthy

  questiondb:
    image: postgres
    environment:
      POSTGRES_USER: ofyenn
      POSTGRES_PASSWORD: ofyenn
      POSTGRES_DB: questions
    volumes:
      - ./db:/var/lib/postgresql/
    healthcheck:
      test: ["CMD", "psql", "-h", "localhost", "-U", "postgres", "-c", "select 1", "airflow"]
      interval: 10s
      timeout: 10s
      retries: 5
